### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by kaphacius** [algal/ALGReversedFlowLayout#1]
Hey. An awesome component, but lacking swift implementation. Can I rewrite it in swift and make a pull request?

**Comment by algal** [comment]
Thanks for the compliment!

I'm a big fan of swift so I write all my new stuff in it. But there are a lot of people who can't use it yet, so it seems a shame to rewrite old things in swift because it introduces a new and (let's face it) unstable dependency on the language runtime and syntax.

What benefit do you see?

Your note does remind me it would be great if this little component were more easy to _use_ from Swift. Right now it lacks nullability annotations, it does not define a framework (which would let someone manage it as an external dependency, perhaps via Carthage), nor does it provide any hints to a beginner who might need a pointer about bridging headers.

**Comment by kaphacius** [comment]
Well, frankly speaking, the only benefit from using swift I saw was using swift itself :). The more people use it - the faster it will become industry standard (provided apple will fix the damn debugger).
I wasn't actually talking about changing the source code from objc to swift, maybe just make a second version?

Well there is a dependency ofc, but it's not like apple updates swift every month. The last one was pretty bad though, lots of compile errors.

**Comment by misbell** [comment]
//
// ReversedFlowLayout.swift
//
// Created by prenez on 5/7/15.
// Copyright (c) 2015 Michael Prenez-Isbell. All rights reserved.
//

import Foundation
import UIKit

/**
ALGReversedFlowLayout is a subclass of UICollectionViewFlowLayout,
but instead of laying out items left-to-right and top-to-bottom,
it lays out items left-to-right and bottom-to-top. It reverses
the layout order not only of rows of cells but also of sections
and of the headers and footers within sections.

*/
class ALGReversedFlowLayout : UICollectionViewFlowLayout {

/**
Expand the collectionViewContentSize to fit the collectionView.bounds. Default is YES.
This will ensure that layout starts from the bottom even when you have manually set the
bounds of the collection to a height larger than needed for its elements.

@discussion

If `expandContentSizeToBounds==NO`, then this layout reverses only the layout
of the collection view's content, i.e., the sections, headers, footers, and rows
of cells. However, this rect of reversed content will itself be placed at the
top of the collection view, because this is the normal behavior of any
`UIScrollView` (of which the `UICollectionView` is a subclass). The result is that,
when the collection view's bounds's size is greater than the content size, the
layout-reversed items will be placed at the top of the view.

If `expandContentSizeToBounds==YES` (the default), then the bottom-to-top layout
starts at the bottom of the UICollectionView.bounds, even when the bounds's size
is bigger than the natural contentSize. It does this by conditionally expanding the
collection view's content size, effectively creating a top inset. (If for some reason
you need the the content size to reflect the natural content size, then you could produce
the same effect by using the `UICollectionView.contentInset.top` property.)

*/
//@property (assign,nonatomic) BOOL expandContentSizeToBounds;

var expandContentSizeToBounds = false

/**
Defines a minimum permiited collectionViewContentSize.height. If non-nil, the
layout will expand the content area to at least this height.

Set this value if you want to ensure that the scrollable content area of the
collection view always has at least a certain height, even a height which may be
larger than the collection view's bounds.

*/
////@property (strong,nonatomic) NSNumber \* minimumContentSizeHeight;
var minimumContentSizeHeight  = 0

required init(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)

```
self.expandContentSizeToBounds = false
self.minimumContentSizeHeight = 0
```

}

override init() {
    super.init()
    self.expandContentSizeToBounds = false
    self.minimumContentSizeHeight = 0

}

override func shouldInvalidateLayoutForBoundsChange(newBounds: CGRect) -> Bool {
    if (self.expandContentSizeToBounds) && (fabsf(Float(self.collectionView!.bounds.size.height) - Float(newBounds.size.height)) > FLT_EPSILON) {
        return true
    }
    else {
        return super.shouldInvalidateLayoutForBoundsChange(newBounds)
    }

}

override func collectionViewContentSize() -> CGSize {

```
var expandedSize = super.collectionViewContentSize()
if self.expandContentSizeToBounds {

    expandedSize.height  = max(expandedSize.height, self.collectionView!.bounds.size.height)
}

if self.minimumContentSizeHeight > 0 {
    expandedSize.height = max(CGFloat(expandedSize.height), CGFloat( self.minimumContentSizeHeight))
}

return  CGSize()
```

}

override func layoutAttributesForItemAtIndexPath(indexPath: NSIndexPath) -> UICollectionViewLayoutAttributes! {
    var attribute : UICollectionViewLayoutAttributes = super.layoutAttributesForItemAtIndexPath(indexPath)
    self.modifyLayoutAttribute(attribute)
    return attribute
}

func modifyLayoutAttribute(attribute: UICollectionViewLayoutAttributes) {

```
let normalCenter = attribute.center
let reversedCenter = self.reversedPointForNormalPoint(normalCenter)
attribute.center = reversedCenter
```

}

func reversedPointForNormalPoint(normalPoint: CGPoint) -> CGPoint {

```
return CGPoint(x:normalPoint.x, y: self.reversedYForNormalY(normalPoint.y))
```

}

func reversedYForNormalY(normalY: CGFloat) -> CGFloat {

```
var YreversedAroundContentSizeCenter = self.collectionViewContentSize().height - normalY
return YreversedAroundContentSizeCenter
```

}

func normalYForReversedY(reversedY: CGFloat) -> CGFloat {
    return reversedYForNormalY(reversedY)
}

override func layoutAttributesForElementsInRect(reversedRect: CGRect) -> [AnyObject]? {

```
let normalRect = normalRectForReversedRect(reversedRect)

let attributes : [UICollectionViewLayoutAttributes] = super.layoutAttributesForElementsInRect(normalRect) as! [UICollectionViewLayoutAttributes]
let newAttributes : [UICollectionViewLayoutAttributes]  = attributes.map{
    self.modifyLayoutAttribute($0)
    return $0
}


return newAttributes
```

}

var _scrollDirection : UICollectionViewScrollDirection?
override var scrollDirection : UICollectionViewScrollDirection {
    get {
        return _scrollDirection!
    }
    set {

```
    assert(scrollDirection == UICollectionViewScrollDirection.Vertical,"horizontal scrolling is not supported")
    super.scrollDirection = newValue
    _scrollDirection = newValue

}
```

}

func reversedRectForNormalRect(normalRect: CGRect) -> CGRect {

```
let size = normalRect.size
let normalTopLeft = normalRect.origin
let reversedBottomLeft = self.reversedPointForNormalPoint(normalTopLeft)
let reversedTopLeft = CGPointMake(reversedBottomLeft.x, reversedBottomLeft.y - size.height)
let reversedRect = CGRectMake(reversedTopLeft.x, reversedTopLeft.y, size.width, size.height)

return reversedRect
```

}

func normalRectForReversedRect(reversedRect: CGRect) -> CGRect {

```
return self.reversedRectForNormalRect(reversedRect)
```

}

func normalPointForReversedPoint(reversedPoint: CGPoint)  -> CGPoint {

```
return self.reversedPointForNormalPoint(reversedPoint)
```

}
}

**Comment by misbell** [comment]
hmm I should actually not be using CGPointMake...oh well, this is a bit of a rough draft.

**Comment by kaphacius** [comment]
well that was kinda unnecessary :)
i did rewrite it as i opened an issue, just wanted to make a pull request :)
